### ISSUE TITLE
Incorrect link for mlebook

### ISSUE THREAD

**Issue by fayolle** [bobeff/programming-math-science#6]
The link for 'Machine Learning Engineering Book' is incorrect. 
It should be: 
http://www.mlebook.com/wiki/doku.php
instead of (currently): 
http://www.mlebook.com/wik

**Comment by bobeff** [comment]
Thank you. I fixed the link.

**Comment by fayolle** [comment]
@bobeff You are welcome. Thank you for preparing this very nice list.
